// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoviesWeb.Data;

#nullable disable

namespace MoviesWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230609145913_SeedGenreToDatabase")]
    partial class SeedGenreToDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MoviesWeb.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("GenreTable");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreationDate = new DateTime(2023, 6, 9, 15, 59, 13, 762, DateTimeKind.Local).AddTicks(3617),
                            Description = "A popular movie genre characterised by thrilling, high-energy and adrenaline-pumping content.",
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            CreationDate = new DateTime(2023, 6, 9, 15, 59, 13, 762, DateTimeKind.Local).AddTicks(3673),
                            Description = "A genre of film that aims to entertain and amuse the audience through humor and light-hearted storytelling.",
                            Name = "Comedy"
                        },
                        new
                        {
                            Id = 3,
                            CreationDate = new DateTime(2023, 6, 9, 15, 59, 13, 762, DateTimeKind.Local).AddTicks(3675),
                            Description = "A genre of film that explores imaginative and speculative concepts often based on scientific and technological advancements.",
                            Name = "Sci-Fi"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
